### PR TITLE
UI Termination for File Upload

### PR DESCRIPTION
**Pull request by swebdevelopment**
Added variable to prevent camera/gallery activity loop
Remove Cancellable Request to Upload File feature to prevent UI Block

### CODE REVIEW

**Comment by shawnmaten** [comment]
Something else has been broken. The picker now closes correctly after using the Camera or Gallery options, but it crashes for every other service. For example if I select Dropbox, the entire app crashes.

**Comment by swebdevelopment** [comment]
will check

**Comment by swebdevelopment** [comment]
will have the solution for this in this PR

**Comment by swebdevelopment** [comment]
Added code Edits for app crash

**Comment by shawnmaten** [comment]
I tested all the integrations and everything looks good to me. Just need @kyuss to check it out.

**Pull request merged**
